# Progect/modules/jenkins/values.yaml
# Кастомна конфігурація Jenkins для Helm релізу.
# Цей файл містить параметри, які будуть передані чарту Jenkins.

controller:
  # Налаштування ресурсів для контролера Jenkins
  resources:
    limits:
      cpu: "1000m"
      memory: "2Gi"
    requests:
      cpu: "500m"
      memory: "1Gi"

  # Налаштування сервісу Jenkins
  service:
    # Тип сервісу: LoadBalancer, NodePort, ClusterIP
    # LoadBalancer дозволяє доступ до Jenkins ззовні кластера.
    type: LoadBalancer
    # Порт HTTP для Jenkins
    port: 8080
    # Порт JNLP для агентів Jenkins
    name: "http" # Ім'я порту для HTTP
    # jnlp:
    #   port: 50000

  # Налаштування Persistent Volume Claim для Jenkins
  persistence:
    enabled: true
    # Розмір сховища
    size: 8Gi
    # Клас сховища (якщо у вас є кастомний StorageClass)
    # storageClassName: "your-storage-class"

  # Налаштування Ingress (якщо ви використовуєте Ingress Controller)
  # ingress:
  #   enabled: false
  #   hostName: jenkins.yourdomain.com
  #   annotations:
  #     kubernetes.io/ingress.class: nginx
  #     nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  #     nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  #   tls:
  #     - secretName: jenkins-tls
  #       hosts:
  #         - jenkins.yourdomain.com

  # Налаштування адміністратора Jenkins
  admin:
    # Створення початкового адміністратора
    enabled: true
    # Ім'я користувача адміністратора
    user: admin
    # Пароль адміністратора (буде згенеровано, якщо не вказано)
    # password: your_initial_admin_password

  # Налаштування плагінів
  # installPlugins:
  #   - kubernetes:1.30.0
  #   - git:4.11.5
  #   - pipeline-utility-steps:2.11.0

# Налаштування агентів Jenkins (якщо ви використовуєте динамічні агенти)
# agent:
#   resources:
#     limits:
#       cpu: "500m"
#       memory: "1Gi"
#     requests:
#       cpu: "250m"
#       memory: "512Mi"
