master:
  # Налаштування ресурсів для Jenkins Master
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1"
      memory: "2Gi"
  serviceType: LoadBalancer # Дозволяє доступ до Jenkins через AWS ELB

agent:
  image: "jenkins/agent:latest" # Базовий образ для Jenkins Agent
  podTemplates:
  - name: "kaniko-builder"
    image: "gcr.io/kaniko-project/executor:v1.9.0-debug"
    serviceAccount: "jenkins-agent" # Ім'я сервісного акаунта, створеного Terraform
    command: ["/bin/sh", "-c"]
    args: ["cat"]
    yaml: |
      apiVersion: v1
      kind: Pod
      metadata:
        labels:
          jenkins/agent: kaniko-builder
      spec:
        # volumeMounts та volumes для kaniko, якщо необхідно зберігати кеш
        # volumes:
        # - name: jenkins-workspace
        #   emptyDir: {} # або PersistentVolumeClaim
        # volumeMounts:
        # - name: jenkins-workspace
        #   mountPath: /workspace
    # env:
    # - name: AWS_SDK_LOAD_CONFIG
    #   value: "true" # Для AWS CLI/SDK в контейнері Kaniko, якщо вони потрібні

rbac:
  install: true
  serviceAccount:
    create: true
    name: "jenkins" # Ім'я ServiceAccount для Jenkins Master